# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e8446e4c796aef30e79d6c5087abbf9868f9b5e979854b3d85659cf21d1361e95ca145a7f4816889ec3bb8a851d61cdb625ef56d525adad831283e1e25ee965

test:
  secret_key_base: 54e5ab9364a22d93d2bdee1c00f8bfdea8c1a67e836dfd5b01cda3e1d47f0b6489f949e82f20fbb30f921a7c9f0b2d3a8af5927b63b9f1d07018ba33867a1944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
