# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed1f7870cb813ea477522ad2661db7c4219124180e38cc3c0924a58e561d3a8961732c9845b51e116633d81d62e7aef601e6d85d7f4022016ab56c103294c04

test:
  secret_key_base: da73379a503161e6f6a42f803ee7c0e234cefe94f93951f259780413b8646869dc7fd8de107ffba733428427ccdcad76fab7ba2cac6165fd0c9167330a3c92bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
