# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc4a63e16c40bbee54c4e5fa42e24898b2421b587f367a169426fe951b1515b201b72714be79364f82a8fa969b46a30df301aa7f786498312361ce4caa8c2dc

test:
  secret_key_base: 5aa5d34f5722f1c35ff338c7cfa9df24916ebc6bcd92a704dc6e348193ccd071703e8c7e031b99d53df67924efd8955c338f8af7e849c9843be8b8b5731778c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
